### ISSUE TITLE
Properly handle subdomains

### ISSUE THREAD

**Issue by bsclifton** [brave/ab2cb#4]
We ran into an issue today where the following rule:
`||api.twitter.com^$third-party,domain=~tweetdeck.com|~twitter.com|~twitter.jp` 

was added with brave/adblock-lists@eb7a15d

This specific rule is **_supposed_** to get converted to:
```
  {
    "trigger": {
      "url-filter": "^[^:]+:(//)?([^/]+.)?api\\.twitter\\.com",
      "load-type": [
        "third-party"
      ],
      "unless-domain": [
        "*.tweetdeck.com", <-- the * here are the relevant parts
        "*.twitter.com",
        "*.twitter.jp"
      ]
    },
    "action": {
      "type": "block"
    }
  },
```
However, it wasn't. It's getting converted to this (missing the wildcard):
```
{
    "trigger": {
      "url-filter": "^[^:]+:(//)?([^/]+.)?api\\.twitter\\.com",
      "load-type": [
        "third-party"
      ],
      "unless-domain": [
        "tweetdeck.com",
        "twitter.com",
        "twitter.jp"
      ]
    },
    "action": {
      "type": "block"
    }
  },
```

We need to fix this behavior - would be great to have a unit test capturing this. @kylehickinson mentioned there is an additional complexity in that we can't have both `if-domain` and `unless-domain` in the same rule. We should scan for occurrences of that happening and handle appropriately

**Comment by bsclifton** [comment]
After this is done, we can do a test and verify if iOS is able to load the latest slimlist rules. We'll need to re-enable the cloudwatch events (at last the build one) and then we can run this manually if needed

**Comment by kylehickinson** [comment]
Should be fixed with https://github.com/brave/ab2cb/commit/5c2ddd9dd09a2f1836a53a340d5139499fd773ce

**Comment by bsclifton** [comment]
Let's keep this open - would be great to test this out and verify that the list looks like how we want. I tried to add some tests, but the existing tests all fail and it's a gigantic PITA on Windows using virtualenv 😛
